### ISSUE TITLE
Issue in Installation

### ISSUE THREAD

**Issue by goyalsaransh97** [peteanderson80/bottom-up-attention#62]
I'm trying to install the model/library in Anaconda environment and am getting the following error: 
"
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 53, in locate_cuda
    for k, v in cudaconfig.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
"
Could you suggest something?

**Comment by chengxili** [comment]
you can change iteritems() to items(), python 2 and 3 mismatch problem
