### ISSUE TITLE
Memory Error on AddAttrsToSceneGraphs function

### ISSUE THREAD

**Issue by CharlotteG95** [peteanderson80/bottom-up-attention#65]
Hi I am running the preprocessing stages in order to use visual genome dataset. I have downloaded the segmented json files via the link within visual_genome_python_driver/local.py however the command ./data/genome/setup_vg.py produces a memory error when run - is there a way around this?

$ data/genome/setup_vg.py
Traceback (most recent call last):
  File "data/genome/setup_vg.py", line 205, in <module>
    vg.AddAttrsToSceneGraphs(dataDir=dataDir)
  File "/nas/users/t0192227/faster-rcnn/data/genome/visual_genome_python_driver/local.py", line 227, in AddAttrsToSceneGraphs
    sg_dict = {sg['image_id']:sg for sg in json.load(f)}
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
MemoryError

Thanks
Charlotte

**Comment by djx2726889** [comment]
I have the same problem!
