### ISSUE TITLE
Could not open test.prototxt

### ISSUE THREAD

**Issue by chlorane** [peteanderson80/bottom-up-attention#71]
I'm using the res-101 network and tools/generate_tsv.py to extract bounding box features to a tab-separated-values (tsv) file. I'm using a new dataset based on cartoon series. 
So I run:
python tools/generate_tsv.py --cfg experiments/cfgs/faster_rcnn_end2end_resnet.yml --def models/vg/ResNet-101/faster_rcnn_end2end/test.prototxt --out test2014_resnet101_faster_rcnn_genome.tsv --net data/faster_rcnn_models/resnet101_faster_rcnn_final.caffemodel --split cartoon

However, when I tried to run generate_tsv.py, an error happened:
Process Process-1:
Traceback (most recent call last):
  File "/home/chlorane/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/chlorane/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "tools/generate_tsv.py", line 162, in generate_tsv
    net = caffe.Net(prototxt, caffe.TEST, weights=weights)
RuntimeError: Could not open file ./models/vg/ResNet-101/faster_rcnn_end2end/test.prototxt

Even if I use the absolute path here, the error still happens. What's wrong and how can I solve it?

**Comment by zihaocode** [comment]
Hi, I had the same problem. You can solve it by change the arges `--def models/vg/ResNet-101/faster_rcnn_end2end/test.prototxt` to `--def models/vg/ResNet-101/faster_rcnn_end2end_final/test.prototxt`. That's work for me!

**Comment by alice-cool** [comment]
https://github.com/peteanderson80/bottom-up-attention/issues/71#issuecomment-542163318

Dear scholar, did you run the result? I got all zero and NAN in the second picture. I am so cunfused 

![image](https://user-images.githubusercontent.com/16870890/124372906-9cf3ff80-dcc0-11eb-9226-430130bb5076.png)
![image](https://user-images.githubusercontent.com/16870890/124372913-abdab200-dcc0-11eb-9cad-0b961a2dd58c.png)
