### ISSUE TITLE
No module named gpu_nms

### ISSUE THREAD

**Issue by Tclz** [peteanderson80/bottom-up-attention#95]
Hi, when i run the generate_tsv.py, i meet the following problem
Traceback (most recent call last):
  File "./tools/generate_tsv.py", line 26, in <module>
    from fast_rcnn.test import im_detect,_get_blobs
  File "/home/vilbert_beta/bottom-up-attention/tools/../lib/fast_rcnn/test.py", line 17, in <module>
    from fast_rcnn.nms_wrapper import nms, soft_nms
  File "/home/vilbert_beta/bottom-up-attention/tools/../lib/fast_rcnn/nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms
What should i do to fix it ? plz help me, thanks in advance! :)

**Comment by alice-cool** [comment]
your caffe environment is not installed completely
